# Generated by Django 3.1.6 on 2021-02-16 01:28

import apps.songs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_auto_20210214_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.songs.models.image_file_path, verbose_name='Tapa'),
        ),
    ]
