# Generated by Django 3.1.6 on 2021-02-14 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Localización', 'verbose_name_plural': 'Localizaciónes'},
        ),
    ]
