# Generated by Django 3.1.6 on 2021-02-16 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20210214_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='state_name',
            field=models.CharField(default='', max_length=100, verbose_name='Estado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
