# Generated by Django 3.1.6 on 2021-02-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20210218_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='location',
        ),
        migrations.AddField(
            model_name='pay',
            name='location',
            field=models.ManyToManyField(to='payments.Location'),
        ),
    ]
