# Generated by Django 3.1.6 on 2021-02-18 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20210218_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='location',
        ),
        migrations.AddField(
            model_name='pay',
            name='location',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='payments.location'),
            preserve_default=False,
        ),
    ]
